#http指定端口
#server.http.port=9002
#https
server:
  port: 1001

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lyf_iron_man?serverTimezone=GMT%2B8
    username: root
    password: 123456789

#mybatis xml 路径
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: iron.man.liuyanfei.entity  # 注意：对应实体类的路径
#  configuration:
#    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
#    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法



mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    #      主键使用数据库自增
    db-config:
      id-type: auto
      #表名是否使用驼峰转下划线命名,只对表名生效（默认开启）
      table-underline: true


      #      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  configuration:
    #    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #表名是否使用驼峰转下划线命名,只对列名名生效（默认开启）
    mapUnderscoreToCamelCase: true






