

server:
  address: 0.0.0.0
  port: 1001

spring:
  application:
    name: iron-man-redis
  redis:
    database: 6
    host: 127.0.0.1
    #      password: test
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 15
        max-wait: 10000
        min-idle: 5
    jedis:
      pool:
        max-active: 1000
        max-idle: 15
        max-wait: 10000
        min-idle: 5